### ISSUE TITLE
Dependency on Python 3.10+

### ISSUE THREAD

**Issue by arora-manish** [redisjohn/redis-cloud-api#2]
❯ rediscapi.py -k keys.json -x logs
  File "rediscapi.py", line 113
    match action:
               ^
SyntaxError: invalid syntax

Issue: match case is only available in Python 3.10 or above (Dependency on Python 3.10+)
Solution: replaced match-case, with IF/ELSE

**Comment by redisjohn** [comment]
Documentation Updated
