### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by arora-manish** [redisjohn/redis-cloud-api#3]
❯ rediscapi.py -k keys.json -x logs
Traceback (most recent call last):
  File "rediscapi.py", line 4, in <module>
    import sys, getopt, requests, json, platform
ModuleNotFoundError: No module named 'requests'

**Issue** : Requests is not a built in module 
**Solution**: 
❯ python3 -m pip install requests
or
❯ sudo pip3 install requests

**Comment by redisjohn** [comment]
documentation updated
